# Change these first
owner: Outlier-org # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository
assignees: # Users to assign downtime issues (optional)
  - phirmware
sites:
  - name: Outlier API
    url: https://api.outlier.org
    icon: https://dashboard.outlier.org/images/logo.png
  - name: Outlier Health
    url: https://api.outlier.org/health
    icon: https://dashboard.outlier.org/images/logo.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://dashboard.outlier.org/images/logo.png
  name: Outlier Uptime
  theme: ocean
  themeUrl: https://example.com/my-custom-theme.css
  introTitle: "**Outlier Status Page**."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
